sim_type: superpixel

########## parameters for paths ##########
# model_path: /media/ps3/chenkaim/checkpoints/copied_models/aperiodic_CondConv-10_11_25T06_03_52
# (1) small model 10/14
# model_path: /media/ps3/chenkaim/checkpoints/copied_models/aperiodic_CondConv_small-10_14_25T06_57_15

# (2) medium model 10/14
# model_path: /media/ps3/chenkaim/checkpoints/copied_models/aperiodic_CondConv_medium-10_14_25T07_06_43

# (3)
model_path: /media/ps3/chenkaim/checkpoints/copied_models/aperiodic_CondConv_30_pml_small-10_16_25T15_21_04

output_path: ./ # change this to a different drive if you need to save big files

########## parameters for the physical simulation ##########
sim_shape: [240, 240, 120] # number of pixels in x, y, z
wavelength: 800 # in nm
dL: 25 # simulation resolution, in nm
pmls: [30, 30, 30, 30, 30, 30] # number of pixels of PML for x_start, x_end, y_start, y_end, z_start, z_end

kwargs: # key word arguments for constructing the problem, defined in the waveguide_bend.py file
  substrate_eps: 2.1025 # 1.45**2
  meta_eps: 7.29 # 2.7**2
  top_medium_eps: 1.0 # 1.0**2
  meta_height_nm: 400
  num_meta_atoms: 20
  source_below_meta_nm: 150
  source_polarization: 'x'
  ln_R: -10 # parameter for PML, don't change

########## parameters for the GMRES solver ##########
max_iter: 500
tol: 1e-4
verbose: True
restart: 40 # if == 0, no restart, otherwise, run restarted GMRES

########## other configs ##########
spins_verification: 1 # if == 1, run simulation in spins as well to verify the results
save_for_plotting: 1 # if == 1, save the solution, src, eps, and final residual for plotting